### ISSUE TITLE
How can i continue old train? 

### ISSUE THREAD

**Issue by mvardin** [hamedhemati/Tacotron-2-Persian#7]
As i recently reading the mozilla tts doc , on training section , they say:

To fine-tune a model, use --restore_path.
`python TTS/bin/train_tacotron.py --config_path TTS/tts/configs/config.json --restore_path /path/to/your/model.pth.tar`
To continue an old training run, use --continue_path.
`python TTS/bin/train_tacotron.py --continue_path /path/to/your/run_folder/`

And now , with this project , how can i continue the old training data?
Thanks

**Comment by mvardin** [comment]
If i change this line

`for epoch in range(self.config["epochs"]):`

to

`for epoch in range(previousEpoch,  self.config["epochs"]):`

so previousEpoch is last epoch that trained, is it okey?

**Comment by hamedhemati** [comment]
Hi! at the time of writing the code I didn't add the model checkpoint loading, but it can be simply added in the `train.py` file inside the `main` function after model initialization to manually load a checkpoint. You just need to provide a key for the checkpoint path (for example `checkpoint_path`) in the config file and load it as below:
```python
model = Tacotron2(**config["model"])

# Load checkpoint if checkpoint_path given:
if config["checkpoint_path"] is not None or config["checkpoint_path"] != "":
     model.load_state_dict(torch.load(config["checkpoint_path"], map_location=torch.device("cpu"))

# Trainer
trainer = TacotronTrainer(config, path_manager, model)
trainer.train()

```

In order to set the start epoch counter to the checkpoint's training epoch, you can change the iterator inside the `train` function of `TacotronTrainer` as below:

```python
start_epoch = self.model.get_step() // 1000
for epoch in range(start_epoch, self.config["epochs"]):
            self._train_epoch(epoch)
            self._eval_epoch(epoch)
```

**Comment by mvardin** [comment]
You save my time, thank you

another question is : the checkpoint_path must be the last checkpoint , is it?

**Comment by mvardin** [comment]
> You save my time, thank you
> 
> another question is : the checkpoint_path must be the last checkpoint , is it?

I passed the last one and its working
Thanks
